apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '2'
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"petclinic-latest:latest","namespace":"petclinicuatdemo"},"fieldPath":"spec.template.spec.containers[?(@.name==\"petclinic\")].image"}]
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: '2020-10-16T06:50:44Z'
  generation: 2
  labels:
    app: petclinic
    app.kubernetes.io/component: petclinic
    app.kubernetes.io/instance: petclinic
  name: petclinic
  namespace: petclinicuatdemo
  resourceVersion: '3006'
  selfLink: /apis/apps/v1/namespaces/petclinicuatdemo/deployments/petclinic
  uid: e9b7669f-0f7b-11eb-8ab0-0699bd63557c
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: petclinic
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        deployment: petclinic
    spec:
      containers:
        - image: >-
            mudaliar20/petclinic@sha256:01b358917c1230e320a3b0398741a5f4446834b3053ed14cb2eb94432c4f4ad5
          imagePullPolicy: IfNotPresent
          name: petclinic
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: '2020-10-16T06:50:46Z'
      lastUpdateTime: '2020-10-16T06:50:46Z'
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: 'True'
      type: Available
    - lastTransitionTime: '2020-10-16T06:50:44Z'
      lastUpdateTime: '2020-10-16T06:50:46Z'
      message: ReplicaSet "petclinic-7d964c9ff4" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: 'True'
      type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
